//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleTrouble {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoubleTrouble.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=13&gt;When you&apos;re leaving, the money you earned this round will be either doubled, or halved.&lt;/size&gt;.
        /// </summary>
        internal static string LandingInfoDiff {
            get {
                return ResourceManager.GetString("LandingInfoDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=13&gt;When you&apos;re leaving, your credits will be either doubled, or halved.&lt;/size&gt;.
        /// </summary>
        internal static string LandingInfoOverall {
            get {
                return ResourceManager.GetString("LandingInfoOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=22&gt;&lt;color=#ff0000&gt;&lt;b&gt;YOU LOSE&lt;/b&gt;&lt;/color&gt;&lt;/size&gt;\r\nYou just lost &lt;b&gt;%i&lt;/b&gt; credits..
        /// </summary>
        internal static string ResultLose {
            get {
                return ResourceManager.GetString("ResultLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=22&gt;&lt;color=#00ff00&gt;&lt;b&gt;YOU WIN&lt;/b&gt;&lt;/color&gt;&lt;/size&gt;\r\nYou just won &lt;b&gt;%i&lt;/b&gt; credits..
        /// </summary>
        internal static string ResultWin {
            get {
                return ResourceManager.GetString("ResultWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSE %i credits.
        /// </summary>
        internal static string SpectateResultLose {
            get {
                return ResourceManager.GetString("SpectateResultLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN +%i credits.
        /// </summary>
        internal static string SpectateResultWin {
            get {
                return ResourceManager.GetString("SpectateResultWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Trouble.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
